// <auto-generated />
using System;
using EcoFashionBackEnd.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoFashionBackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250712155149_InitialCreated")]
    partial class InitialCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certificates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationPictureOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIdentificationVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioFiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialLinks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecializationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetRoleId")
                        .HasColumnType("int");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("TargetRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.Design", b =>
                {
                    b.Property<int>("DesignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignId"));

                    b.Property<string>("CareInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DesignerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductScore")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("RecycledPercentage")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignId");

                    b.HasIndex("DesignerId");

                    b.ToTable("Designs");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignImage", b =>
                {
                    b.Property<int>("DesignImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignImageId"));

                    b.Property<int>("DesignId")
                        .HasColumnType("int");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.HasKey("DesignImageId");

                    b.HasIndex("ImageId");

                    b.HasIndex("DesignId", "ImageId")
                        .IsUnique();

                    b.ToTable("Design_Image");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignType", b =>
                {
                    b.Property<int>("DesignTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignTypeId"));

                    b.Property<string>("DesignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Meter")
                        .HasColumnType("real");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("DesignTypeId");

                    b.HasIndex("SizeId");

                    b.ToTable("Design_Type");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.Designer", b =>
                {
                    b.Property<Guid>("DesignerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certificates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesignerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationPictureOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioFiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("SpecializationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DesignerId");

                    b.HasIndex("UserId");

                    b.ToTable("Designer");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Designs_Color");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsFeature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureId"));

                    b.Property<int>("DesignId")
                        .HasColumnType("int");

                    b.Property<bool>("Durable")
                        .HasColumnType("bit");

                    b.Property<bool>("EthicallyManufactured")
                        .HasColumnType("bit");

                    b.Property<bool>("LowImpactDyes")
                        .HasColumnType("bit");

                    b.Property<int>("RecycledMaterials")
                        .HasColumnType("int");

                    b.Property<bool>("ReduceWaste")
                        .HasColumnType("bit");

                    b.HasKey("FeatureId");

                    b.HasIndex("DesignId")
                        .IsUnique();

                    b.ToTable("Designs_Feature");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsMaterial", b =>
                {
                    b.Property<int>("DesignIdPk")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("SavedMaterialIdPk")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("DesignId")
                        .HasColumnType("int");

                    b.Property<float>("PersentageUsed")
                        .HasColumnType("real");

                    b.Property<int>("SavedMaterialId")
                        .HasColumnType("int");

                    b.HasKey("DesignIdPk", "SavedMaterialIdPk");

                    b.HasIndex("DesignId");

                    b.ToTable("Designs_Materials");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsRating", b =>
                {
                    b.Property<int>("DesignIdPk")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CustomerIdPk")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DesignId")
                        .HasColumnType("int");

                    b.Property<float>("RatingScore")
                        .HasColumnType("real");

                    b.HasKey("DesignIdPk", "CustomerIdPk");

                    b.HasIndex("DesignId");

                    b.ToTable("Designs_Rating");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SizeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Designs_Size");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsVarient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CarbonFootprint")
                        .HasColumnType("real");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("DesignId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<float>("WasteDiverted")
                        .HasColumnType("real");

                    b.Property<float>("WaterUsage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("DesignId");

                    b.HasIndex("SizeId");

                    b.ToTable("Designs_Varient");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certificates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentificationPictureOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioFiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("SpecializationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.TypeSize", b =>
                {
                    b.Property<int>("DesignTypeIdPk")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("SizeIdPk")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("DesignTypeId")
                        .HasColumnType("int");

                    b.Property<float>("Meter")
                        .HasColumnType("real");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("DesignTypeIdPk", "SizeIdPk");

                    b.HasIndex("DesignTypeId");

                    b.HasIndex("SizeId");

                    b.ToTable("Type_Size");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OTPCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("OTPExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("SavedSupplier", b =>
                {
                    b.Property<Guid>("SavedSupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DesignerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SavedSupplierId");

                    b.HasIndex("DesignerId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Saved_Supplier");
                });

            modelBuilder.Entity("Application", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("TargetRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoFashionBackEnd.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.Design", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.Designer", "DesignerProfile")
                        .WithMany()
                        .HasForeignKey("DesignerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignerProfile");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignImage", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.Design", "Design")
                        .WithMany("DesignImages")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoFashionBackEnd.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignType", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.DesignsSize", "DesignsSize")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DesignsSize");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.Designer", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsFeature", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.Design", "Design")
                        .WithOne("DesignsFeature")
                        .HasForeignKey("EcoFashionBackEnd.Entities.DesignsFeature", "DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsMaterial", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.Design", "Design")
                        .WithMany("DesignsMaterials")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsRating", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.Design", "Design")
                        .WithMany("DesignsRatings")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.DesignsVarient", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.DesignsColor", "DesignsColor")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoFashionBackEnd.Entities.Design", "Design")
                        .WithMany("DesignsVarients")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoFashionBackEnd.Entities.DesignsSize", "DesignsSize")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");

                    b.Navigation("DesignsColor");

                    b.Navigation("DesignsSize");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.Supplier", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.TypeSize", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.DesignType", null)
                        .WithMany()
                        .HasForeignKey("DesignTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoFashionBackEnd.Entities.DesignsSize", null)
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.User", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("SavedSupplier", b =>
                {
                    b.HasOne("EcoFashionBackEnd.Entities.Designer", "Designer")
                        .WithMany()
                        .HasForeignKey("DesignerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EcoFashionBackEnd.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Designer");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("EcoFashionBackEnd.Entities.Design", b =>
                {
                    b.Navigation("DesignImages");

                    b.Navigation("DesignsFeature")
                        .IsRequired();

                    b.Navigation("DesignsMaterials");

                    b.Navigation("DesignsRatings");

                    b.Navigation("DesignsVarients");
                });
#pragma warning restore 612, 618
        }
    }
}
